Repository Megh2005/Med-o-Next, pull requests merged in 2024-10, with the labels that each got.

#45 Enhanced chat features: send message on ENTER keypress, edit and delete message functionalities
  package-lock.json
  src/app/api/delete-message/route.ts
  src/app/api/edit-message/route.ts
  src/components/ChatInput.tsx
  src/components/ChatMessage.tsx
  src/components/MessagesContainer.tsx
  src/lib/features/conversations/conversationsSlice.ts
  src/services/firebase/config.ts
Labels: enhancement, gssoc-ext, level 2, hactoberfest-accepted, Feature Addition

#74 Mini Chatbot Added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/page.tsx
  frontend/src/components/MiniChatbot.tsx
Labels: enhancement, level 2, hactoberfest, hactoberfest-accepted, Feature Addition

#131 Add feature: sticky navbar and footer.
  frontend/src/components/landing-page.tsx
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, hactoberfest, hactoberfest-accepted, level 1

#139 Documentation: Enhancement Of Contributing.md
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, hactoberfest, hactoberfest-accepted, level 1

#143 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext, hactoberfest, hactoberfest-accepted, level 1
